### PR TITLE
Move license information to a separate file

### PR DESCRIPTION
**Pull request by jeremydaily**

### CODE REVIEW

**Comment by jeremydaily** [comment]
Addresses issue #3

**Comment by BenGardiner** [comment]
Your changes aren't quite what is conventional for github repos

https://help.github.com/articles/adding-a-license-to-a-repository/

 I added a commit that I think would tract those conventions better. 

PS addresses #1 actually

**Review by BenGardiner — APPROVED** [review]
with proposed changes as in the added commit, approved

**Comment by jeremydaily** [comment]
Looks good

**Pull request merged**
